import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import LogoStrip from "@/components/LogoStrip";
import CartProvider from "@/components/cart/CartProvider";
import SupportChat from "@/components/SupportChat";
import PreviewTimeout from "@/components/PreviewTimeout";

import "@/styles/preview-timeout.css";

import "@/styles/globals.css";
import "@/styles/layout.css";
import "@/styles/header.css";
import "@/styles/mobile-menu.css";
import "@/styles/support-chat.css";
import "@/data/catalog.css";
import "@/styles/products.css";
import "@/styles/product-page.css";
import "@/styles/cart.css";
import "@/styles/buttons.css";
import "@/styles/responsive.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full app-body">
        <CartProvider>
          
          <Header />
          <main className="app-main">{children}</main>
          <LogoStrip />
          <Footer />
          <SupportChat />
        </CartProvider>
    </body>
  </html>
);
}
