import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import LogoStrip from "@/components/LogoStrip";
import CartProvider from "@/components/cart/CartProvider";
import SupportChat from "@/components/SupportChat";

import "./globals.css";
import "./layout.css";
import "./header.css";
import "./mobile-menu.css";
import "./support-chat.css";
import "./catalog.css";
import "./products.css";
import "./product-page.css";
import "./cart.css";
import "./buttons.css";
import "./responsive.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full app-body">
        <CartProvider>
          <Header />
          <main className="app-main">{children}</main>
          <LogoStrip />
<Footer />
<SupportChat />
        
        </CartProvider>
    </body>
  </html>
);
}
